# Generated by Django 6.1 on 2026-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='association_name',
            field=models.CharField(blank=True, db_index=True, default='Ganesh Youth Association', help_text='Youth association / committee name (e.g. Sri Veera Bhadra Swamy Youth)', max_length=200),
        ),
    ]
