# Generated by Django 6.1 on 2026-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Festival name in English, e.g., "Ganesh Chanda 2026"', max_length=100)),
                ('name_telugu', models.CharField(blank=True, help_text='Festival name in Telugu, e.g., "గణేష్ చందా 2026"', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Festival year (e.g., 2026). Must be unique.', unique=True)),
                ('start_date', models.DateField(blank=True, help_text='When donation collection starts', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When the festival ends', null=True)),
                ('location', models.CharField(blank=True, help_text='Location of the Ganesh pandal', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only ONE festival should be active at a time (current year)')),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for receiving donations, e.g., "ganeshyouth@phonepe"', max_length=100)),
                ('qr_code_image', models.ImageField(blank=True, help_text='QR code image for UPI payments', null=True, upload_to='qr_codes/')),
            ],
            options={
                'db_table': 'festivals',
                'ordering': ['-year'],
            },
        ),
    ]
