# Generated by Django 6.1 on 2026-08-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='association_name',
            field=models.CharField(blank=True, default='Ganesh Youth Association', help_text='Youth association / committee name, e.g., "Jai Hind Ganesh Youth Association"', max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='association_name_telugu',
            field=models.CharField(blank=True, default='గణేష్ యువజన సంఘం', help_text='Youth association name in Telugu', max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark or specific stage spot', max_length=200),
        ),
        migrations.AlterField(
            model_name='festival',
            name='location',
            field=models.CharField(blank=True, help_text='Location / Colony / Street of the Ganesh pandal', max_length=200),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the youth committee member', max_length=150)),
                ('name_telugu', models.CharField(blank=True, help_text='Member name in Telugu', max_length=150)),
                ('designation', models.CharField(choices=[('PRESIDENT', 'President / అధ్యక్షుడు'), ('VICE_PRESIDENT', 'Vice President / ఉపాధ్యక్షుడు'), ('SECRETARY', 'General Secretary / ప్రధాన కార్యదర్శి'), ('JOINT_SECRETARY', 'Joint Secretary / సహాయ కార్యదర్శి'), ('TREASURER', 'Treasurer / కోశాధికారి'), ('ADVISOR', 'Advisor / గౌరవ సలహాదారు'), ('YOUTH_LEADER', 'Youth Leader / యువజన నాయకుడు'), ('EXECUTIVE_MEMBER', 'Executive Member / కార్యవర్గ సభ్యుడు'), ('MEMBER', 'Member / సభ్యుడు'), ('VOLUNTEER', 'Volunteer / స్వచ్ఛంద సేవకుడు')], default='MEMBER', help_text='Role/Designation in the Ganesh Youth Committee', max_length=50)),
                ('custom_designation', models.CharField(blank=True, help_text='Optional custom designation in English', max_length=100)),
                ('custom_designation_telugu', models.CharField(blank=True, help_text='Optional custom designation in Telugu', max_length=100)),
                ('mobile_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which member appears on committee list & banners')),
                ('is_active', models.BooleanField(default=True, help_text='Is active member for this year')),
                ('festival', models.ForeignKey(help_text='Festival year this committee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='festivals.festival')),
            ],
            options={
                'db_table': 'committee_members',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
