# Generated by Django 6.1 on 2026-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_festival_association_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='photo',
            field=models.TextField(blank=True, help_text='Base64 or photo URL of committee member'),
        ),
    ]
