# Generated by Django 6.1 on 2026-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_committeemember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='qr_code_image',
            field=models.TextField(blank=True, default='', help_text='Base64 QR code image or URL for UPI payments'),
        ),
    ]
