# Generated by Django 5.1.15 on 2026-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_alter_festival_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Only ONE festival should be active at a time per association'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='year',
            field=models.PositiveIntegerField(help_text='Festival year (e.g., 2026).'),
        ),
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.UniqueConstraint(fields=('year', 'association_name'), name='unique_year_per_association'),
        ),
    ]
