# Generated by Django 6.1 on 2026-08-16 14:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than zero.')])),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_expenses', to='expenses.expensecategory')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_expenses', to='festivals.festival')),
            ],
            options={
                'db_table': 'planned_expenses',
                'ordering': ['category__display_order'],
                'unique_together': {('festival', 'category')},
            },
        ),
    ]
