# Generated by Django 6.1 on 2026-08-14 05:14

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Full name of the donor', max_length=150)),
                ('mobile_number', models.CharField(blank=True, help_text='10-digit mobile number (optional)', max_length=15, validators=[common.validators.validate_mobile_number])),
                ('address', models.TextField(blank=True, help_text='Donor address (optional)')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the donor (not shown publicly)')),
            ],
            options={
                'db_table': 'donors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_donor_name'), models.Index(fields=['mobile_number'], name='idx_donor_mobile')],
            },
        ),
    ]
