import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appTitle: 'Ganesh Chanda System',
    appSubtitle: 'Financial & Donation Management',
    dashboard: 'Dashboard',
    donations: 'Donations',
    donors: 'Donors',
    expenses: 'Expenses',
    planning: 'Budget & Planning',
    reports: 'Financial Reports',
    festivals: 'Festivals & Events',
    committee: 'Youth Committee',
    settings: 'Pandal & Settings',
    auditLogs: 'Audit Logs',
    publicPortal: 'Public Portal',
    login: 'Sign In',
    logout: 'Sign Out',
    username: 'Username',
    password: 'Password',
    welcome: 'Welcome',
    role: 'Role',
    admin: 'Administrator',
    treasurer: 'Treasurer',
    collector: 'Collector',
    totalDonations: 'Total Collections',
    totalExpenses: 'Total Expenses',
    netBalance: 'Available Balance',
    totalDonors: 'Total Donors',
    todayCollection: 'Today Collection',
    todayExpenses: 'Today Expenses',
    todayNet: 'Today Net',
    activeFestival: 'Active Festival',
    noActiveFestival: 'No active festival selected',
    addDonation: 'Record Donation',
    addExpense: 'Add Expense',
    addDonor: 'Add Donor',
    addMember: 'Add Committee Member',
    donorName: 'Donor Name',
    amount: 'Amount (₹)',
    paymentMethod: 'Payment Method',
    transactionId: 'Transaction ID / UTR',
    donationDate: 'Donation Date',
    expenseDate: 'Expense Date',
    category: 'Category',
    description: 'Description',
    receiptNo: 'Receipt No',
    collectedBy: 'Collected By',
    actions: 'Actions',
    search: 'Search by donor name, receipt #...',
    filter: 'Filter',
    all: 'All',
    cash: 'Cash',
    phonepe: 'PhonePe',
    gpay: 'Google Pay',
    upi: 'UPI',
    qr: 'QR Code',
    bank: 'Bank Transfer',
    other: 'Other',
    downloadPdf: 'Download PDF Receipt',
    printReceipt: 'Print Receipt',
    exportExcel: 'Export to Excel',
    dailyReport: 'Daily Report',
    monthlyReport: 'Monthly Report',
    comparisonReport: 'Year-over-Year Comparison',
    plannedVsActual: 'Budget vs Actual Expenses',
    projectedBalance: 'Projected Balance',
    budgetAlert: 'Deficit Warning: Planned expenses exceed available balance!',
    status: 'Status',
    confirmed: 'Confirmed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No records found',
    successSaved: 'Successfully recorded!',
    errorOccurred: 'An error occurred. Please check your input.',
    publicNotice: 'Transparency Portal for Ganesh Chanda Community & Devotees',
    pandalLocation: 'Pandal & Stage Location',
    associationName: 'Youth Association Name',
  },
  te: {
    appTitle: 'గణేష్ చందా నిర్వహణ',
    appSubtitle: 'చందాలు మరియు ఖర్చుల లెక్కల వ్యవస్థ',
    dashboard: 'డాష్‌బోర్డ్',
    donations: 'చందాలు',
    donors: 'దాతలు',
    expenses: 'ఖర్చులు',
    planning: 'బడ్జెట్ & ప్రణాళిక',
    reports: 'ఆర్థిక నివేదికలు',
    festivals: 'ఉత్సవాలు',
    committee: 'యువజన సంఘం కమిటీ',
    settings: 'మండపం & సెట్టింగ్స్',
    auditLogs: 'ఆడిట్ లాగ్స్',
    publicPortal: 'పబ్లిక్ పోర్టల్',
    login: 'లాగిన్',
    logout: 'లాగౌట్',
    username: 'వినియోగదారుని పేరు',
    password: 'పాస్‌వర్డ్',
    welcome: 'స్వాగతం',
    role: 'హోదా',
    admin: 'అడ్మినిస్ట్రేటర్',
    treasurer: 'కోశాధికారి (Treasurer)',
    collector: 'వసూలుదారు (Collector)',
    totalDonations: 'మొత్తం వసూలైన చందాలు',
    totalExpenses: 'మొత్తం ఖర్చులు',
    netBalance: 'మిగిలిన నిల్వ (Balance)',
    totalDonors: 'మొత్తం దాతలు',
    todayCollection: 'ఈరోజు వసూలు',
    todayExpenses: 'ఈరోజు ఖర్చులు',
    todayNet: 'ఈరోజు నికర నిల్వ',
    activeFestival: 'ప్రస్తుత ఉత్సవం',
    noActiveFestival: 'యాక్టివ్ ఉత్సవం లేదు',
    addDonation: 'చందా నమోదు చేయండి',
    addExpense: 'ఖర్చు నమోదు చేయండి',
    addDonor: 'కొత్త దాత నమోదు',
    addMember: 'కమిటీ సభ్యుడిని చేర్చండి',
    donorName: 'దాత పేరు',
    amount: 'మొత్తం (₹)',
    paymentMethod: 'చెల్లింపు విధానం',
    transactionId: 'ట్రాన్సాక్షన్ ID',
    donationDate: 'చందా తేదీ',
    expenseDate: 'ఖర్చు తేదీ',
    category: 'వర్గం (Category)',
    description: 'వివరాలు',
    receiptNo: 'రసీదు నంబర్',
    collectedBy: 'వసూలు చేసినవారు',
    actions: 'చర్యలు',
    search: 'దాత పేరు లేదా రసీదు నంబర్ తో శోధించండి...',
    filter: 'ఫిల్టర్',
    all: 'అన్నీ',
    cash: 'నగదు (Cash)',
    phonepe: 'PhonePe',
    gpay: 'Google Pay',
    upi: 'UPI',
    qr: 'QR కోడ్',
    bank: 'బ్యాంక్ బదిలీ',
    other: 'ఇతరాలు',
    downloadPdf: 'PDF రసీదు డౌన్‌లోడ్',
    printReceipt: 'రసీదు ముద్రించండి',
    exportExcel: 'Excel ఎక్స్‌పోర్ట్',
    dailyReport: 'రోజువారీ నివేదిక',
    monthlyReport: 'నెలవారీ నివేదిక',
    comparisonReport: 'సంవత్సరాల వారీ పోలిక',
    plannedVsActual: 'బడ్జెట్ vs వాస్తవ ఖర్చులు',
    projectedBalance: 'అంచనా మిగులు నిల్వ',
    budgetAlert: 'హెచ్చరిక: ప్రణాళికా ఖర్చులు అందుబాటులో ఉన్న నిల్వ కంటే ఎక్కువ!',
    status: 'స్థితి',
    confirmed: 'ధృవీకరించబడింది',
    pending: 'పెండింగ్',
    cancelled: 'రద్దు చేయబడింది',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు',
    close: 'మూసివేయి',
    loading: 'లోడ్ అవుతోంది...',
    noData: 'ఎటువంటి వివరాలు లభించలేదు',
    successSaved: 'విజయవంతంగా నమోదు చేయబడింది!',
    errorOccurred: 'లోపం జరిగింది. దయచేసి వివరాలను సరిచూసుకోండి.',
    publicNotice: 'గణేష్ భక్తులందరి కోసం పారదర్శక నివేదికల పోర్టల్',
    pandalLocation: 'మండపం మరియు వేదిక ప్రదేశం',
    associationName: 'యువజన సంఘం పేరు',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('gms_language') || 'en';
  });

  const toggleLanguage = () => {
    const newLang = lang === 'en' ? 'te' : 'en';
    setLang(newLang);
    localStorage.setItem('gms_language', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
