# Generated by Django 6.1 on 2026-08-14 05:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('festivals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in INR (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than zero.')])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('PHONEPE', 'PhonePe'), ('GPAY', 'Google Pay'), ('UPI', 'UPI'), ('QR', 'QR Code'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', help_text='How the donation was paid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction/reference ID for digital payments', max_length=100)),
                ('payment_app', models.CharField(blank=True, help_text='Payment app name (PhonePe, Google Pay, etc.)', max_length=50)),
                ('donation_date', models.DateField(help_text='Date the donation was received')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Donation status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this donation')),
                ('collected_by', models.ForeignKey(help_text='Committee member who collected this donation', on_delete=django.db.models.deletion.PROTECT, related_name='collected_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(help_text='Who made this donation', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.donor')),
                ('festival', models.ForeignKey(help_text='Which Ganesh Chanda year this donation belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='festivals.festival')),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(help_text='Unique receipt number, e.g., GCH-2026-0001', max_length=20, unique=True)),
                ('donation', models.OneToOneField(help_text='The donation this receipt is for', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.donation')),
                ('festival', models.ForeignKey(help_text='Festival year (denormalized for faster receipt queries)', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='festivals.festival')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['festival', 'donation_date'], name='idx_donation_festival_date'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['festival', 'payment_method'], name='idx_donation_payment'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['collected_by', 'festival'], name='idx_donation_collector'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'festival'], name='idx_donation_donor'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='idx_receipt_number'),
        ),
    ]
