# Generated by Django 6.1 on 2026-08-16 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='collector_member_name',
            field=models.CharField(blank=True, help_text='Youth committee member or volunteer who physically collected this chanda', max_length=150),
        ),
        migrations.AlterField(
            model_name='donation',
            name='collected_by',
            field=models.ForeignKey(help_text='System user who logged this donation', on_delete=django.db.models.deletion.PROTECT, related_name='collected_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
