# Generated by Django 6.1 on 2026-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_collector_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='auction_item',
            field=models.CharField(blank=True, help_text='Item won in Velam Paata (e.g. Maha Laddu, Small Laddu, Left/Right Tinkayya, Fruits)', max_length=150),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('CHANDA', 'General Chanda / సాధారణ చందా'), ('VELAM_PAATA', 'Velam Paata (Auction) / వేలం పాట'), ('ANNADHANAM', 'Annadanam / అన్నదానం'), ('POOJA', 'Special Pooja / పూజ')], default='CHANDA', help_text='Type of contribution', max_length=50),
        ),
    ]
