# Generated by Django 5.2.17 on 2026-09-02 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_auction_item_donation_donation_type'),
        ('donors', '0001_initial'),
        ('festivals', '0004_alter_festival_qr_code_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['festival', 'donation_type'], name='idx_donation_festival_type'),
        ),
    ]
