# Generated by Django 6.1 on 2026-08-16 13:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name in English', max_length=100, unique=True)),
                ('name_telugu', models.CharField(blank=True, help_text='Category name in Telugu', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from dropdowns')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear in dropdowns')),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'db_table': 'expense_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(help_text='What was this expense for (e.g., "Main stage decoration")', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in INR (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than zero.')])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('PHONEPE', 'PhonePe'), ('GPAY', 'Google Pay'), ('UPI', 'UPI'), ('QR', 'QR Code'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction/reference ID for digital payments', max_length=100)),
                ('expense_date', models.DateField(help_text='Date the expense was made')),
                ('notes', models.TextField(blank=True)),
                ('festival', models.ForeignKey(help_text='Which festival year this expense belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='festivals.festival')),
                ('paid_by', models.ForeignKey(help_text='Committee member who paid this expense', on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Expense category (Decoration, Food, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['festival', 'expense_date'], name='idx_expense_festival_date'), models.Index(fields=['festival', 'category'], name='idx_expense_category')],
            },
        ),
    ]
