# Generated by Django 6.1 on 2026-08-17 06:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('FULLY_PAID', 'Fully Paid / పూర్తిగా చెల్లించబడింది'), ('ADVANCE_PAID', 'Advance Paid / అడ్వాన్స్ చెల్లింపు'), ('PARTIAL_PAID', 'Partially Paid / పాక్షిక చెల్లింపు'), ('PENDING', 'Payment Pending / బకాయి')], default='FULLY_PAID', help_text='Payment stage status', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total agreed cost/price with vendor (e.g. ₹25,000 for Ganesh Idol)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_contact',
            field=models.CharField(blank=True, help_text='Vendor phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Vendor / Artist / Shop name (e.g. Dhoolpet Murti Kendra, Sai Sounds)', max_length=150),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Expense amount / Advance paid in INR (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than zero.')]),
        ),
    ]
